'use strict';
// App + tray icons from assets/icon (generated by assets/icon/make_icons.py; master = icon.svg).
// nativeImage.createFromPath picks up the tray@1.25x / @1.5x / @2x siblings automatically.
const path = require('path');
const { nativeImage } = require('electron');

const ICON_DIR = path.join(__dirname, '..', '..', 'assets', 'icon');
const load = (file) => nativeImage.createFromPath(path.join(ICON_DIR, file));
// Windows: ICO so the tray gets the exact 16/20/24/32 frame per DPI; elsewhere PNG + @Nx siblings.
const TRAY_EXT = process.platform === 'win32' ? '.ico' : '.png';

module.exports = {
  ICON_DIR,
  trayIcon: () => load('tray' + TRAY_EXT),
  trayPausedIcon: () => load('tray-paused' + TRAY_EXT),
  windowIcon: () => load('icon.ico'),
  notifyIcon: () => load('icon-256.png'),
};
