'use strict';
// Web build (GitHub Pages): node scripts/build-web.js → web-dist/
// The web version runs the SAME renderer pages and the SAME main-process controller (src/main/app.js)
// in the browser: a tiny CommonJS bundler packs app.js + preload.js + src/core with shims for
// electron/fs/path/url (src/web/*). Every emitted path is relative, so the site works under /breakfit/.
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const OUT = path.join(ROOT, 'web-dist');
const rel = (p) => path.relative(ROOT, p).split(path.sep).join('/');

// ---------- bundle ----------
// Bare / node specifiers → web shims. Everything else must be a relative file inside the repo.
const ALIAS = {
  electron: 'src/web/electron-main.js',
  fs: 'src/web/fs.js',
  path: 'src/web/path.js',
  url: 'src/web/url.js',
};
const ENTRIES = ['src/web/host.js', 'src/main/app.js', 'src/main/preload.js'];

function resolve(from, spec) {
  if (ALIAS[spec]) return ALIAS[spec];
  if (!spec.startsWith('.')) throw new Error(`${from}: no web shim for require('${spec}')`);
  const base = path.join(ROOT, path.dirname(from), spec);
  for (const f of [base, `${base}.js`, `${base}.json`, path.join(base, 'index.js')]) {
    if (fs.existsSync(f) && fs.statSync(f).isFile()) return rel(f);
  }
  throw new Error(`${from}: cannot resolve '${spec}'`);
}

// siteFiles: every file copied under assets/ ('/assets/clips/x.mp4'), so the fs shim can answer
// existsSync for clips honestly (a clip still being cut shows the placeholder instead of a 404).
function bundle(siteFiles = []) {
  const mods = {};
  const todo = [...ENTRIES];
  while (todo.length) {
    const id = todo.pop();
    if (mods[id]) continue;
    const src = fs.readFileSync(path.join(ROOT, id), 'utf8');
    if (id.endsWith('.json')) { mods[id] = { code: `module.exports = ${src.trim()};`, deps: {} }; continue; }
    const deps = {};
    for (const m of src.matchAll(/\brequire\(\s*['"]([^'"]+)['"]\s*\)/g)) {
      deps[m[1]] = resolve(id, m[1]);
      todo.push(deps[m[1]]);
    }
    mods[id] = { code: src, deps };
  }
  const body = Object.keys(mods).sort().map((id) => `${JSON.stringify(id)}: [${JSON.stringify(mods[id].deps)}, function (module, exports, require, __dirname) {\n${mods[id].code}\n}]`);
  return `// BreakFit web bundle (generated by scripts/build-web.js — do not edit)
(function () {
'use strict';
var process = { platform: 'web', argv: [], env: {}, versions: {} };
var __bfSiteFiles = new Set(${JSON.stringify(siteFiles)});
var MODS = {
${body.join(',\n')}
};
// load(id, cache): cache lets the preload run once per page with that page's own electron shim.
function load(id, cache) {
  if (cache[id]) return cache[id].exports;
  var m = { exports: {} };
  cache[id] = m;
  var def = MODS[id];
  def[1].call(m.exports, m, m.exports, function (spec) { return load(def[0][spec], cache); }, '/' + id.replace(/\\/[^/]*$/, ''));
  return m.exports;
}
window.__bfLoad = load;
load('src/web/host.js', {});
}());
`;
}

// ---------- assets ----------
function copy(src, dst) {
  fs.mkdirSync(path.dirname(dst), { recursive: true });
  fs.copyFileSync(src, dst);
}

// A font stylesheet from node_modules plus only the font files it references.
function copyCss(relCss) {
  const src = path.join(ROOT, 'node_modules', relCss);
  const dst = path.join(OUT, 'lib', relCss);
  copy(src, dst);
  const css = fs.readFileSync(src, 'utf8');
  for (const m of css.matchAll(/url\(\s*["']?([^"')]+)["']?\s*\)/g)) {
    if (/^(data:|https?:)/.test(m[1])) continue;
    const f = path.join(path.dirname(src), m[1]);
    if (fs.existsSync(f)) copy(f, path.join(path.dirname(dst), m[1]));
  }
}

// Every page gets the bundle before its first script (theme.js needs window.bf) and, when
// src/web/<page>.css exists, a web-only stylesheet after its own ones.
// fromRoot = the page's path prefix back to web-dist/.
function webPage(html, { name, fromRoot, scriptDir }) {
  let out = html
    .replace(/(["'])(?:\.\.\/)+node_modules\//g, `$1${fromRoot}lib/`)
    .replace(/ file:/g, ''); // CSP: 'self' only on the web
  if (scriptDir) {
    out = out
      .replace(/(<script src=")(?!https?:|\.\.?\/)([^"]+\.js")/g, `$1${scriptDir}$2`)
      .replace(/(<script src=")(\.\.\/[^"]+\.js")/g, `$1${scriptDir}$2`) // ../i18n.js → src/renderer/../i18n.js
      .replace(/(<link rel="stylesheet" href=")(?!https?:|\.\.?\/|lib\/)([^"]+\.css")/g, `$1${scriptDir}$2`);
  }
  const inject = `<script src="${fromRoot}web.js"></script>\n`;
  const i = out.search(/<script src=/);
  if (i < 0) throw new Error('page has no <script> to anchor the web bundle');
  out = out.slice(0, i) + inject + out.slice(i);
  const css = path.join(ROOT, 'src/web', `${name}.css`);
  if (fs.existsSync(css)) {
    copy(css, path.join(OUT, 'web', `${name}.css`));
    out = out.replace('</head>', `<link rel="stylesheet" href="${fromRoot}web/${name}.css">\n</head>`);
  }
  return out;
}

function build() {
  fs.rmSync(OUT, { recursive: true, force: true });
  fs.mkdirSync(OUT, { recursive: true });
  const ASSET_DIRS = ['assets/clips', 'assets/icon'];
  const assetFiles = ASSET_DIRS.flatMap((dir) => fs.readdirSync(path.join(ROOT, dir))
    .filter((f) => fs.statSync(path.join(ROOT, dir, f)).isFile() && /\.(mp4|jpg|png|svg|ico)$/.test(f) && !/^concepts/.test(f))
    .map((f) => `${dir}/${f}`));
  fs.writeFileSync(path.join(OUT, 'web.js'), bundle(assetFiles.map((f) => `/${f}`)));

  // fonts: every node_modules stylesheet a renderer page links
  const R = path.join(ROOT, 'src/renderer');
  const css = new Set();
  for (const f of fs.readdirSync(R)) {
    if (!f.endsWith('.html')) continue;
    for (const m of fs.readFileSync(path.join(R, f), 'utf8').matchAll(/node_modules\/([^"']+\.css)/g)) css.add(m[1]);
  }
  for (const c of css) copyCss(c);

  // renderer pages (overlay/cover load in an in-page frame at their own path) + scripts/styles
  for (const f of fs.readdirSync(R)) {
    const src = path.join(R, f);
    const dst = path.join(OUT, 'src/renderer', f);
    if (f.endsWith('.html')) {
      fs.mkdirSync(path.dirname(dst), { recursive: true });
      fs.writeFileSync(dst, webPage(fs.readFileSync(src, 'utf8'), { name: f.replace(/\.html$/, ''), fromRoot: '../../' }));
    } else copy(src, dst);
  }
  // shared strings (renderer pages load ../i18n.js; the bundle has its own copy via require)
  copy(path.join(ROOT, 'src/i18n.js'), path.join(OUT, 'src/i18n.js'));
  // index.html = the main window, served from the site root
  const main = fs.readFileSync(path.join(R, 'main.html'), 'utf8');
  let index = webPage(main, { name: 'main', fromRoot: '', scriptDir: 'src/renderer/' });
  index = index.replace('initial-scale=1">', 'initial-scale=1, viewport-fit=cover">')
    .replace('</head>', '<link rel="icon" href="assets/icon/icon-256.png">\n</head>');
  fs.writeFileSync(path.join(OUT, 'index.html'), index);

  for (const f of assetFiles) copy(path.join(ROOT, f), path.join(OUT, f));
  fs.writeFileSync(path.join(OUT, '.nojekyll'), '');
  let n = 0;
  let bytes = 0;
  (function walk(d) {
    for (const e of fs.readdirSync(d, { withFileTypes: true })) {
      const p = path.join(d, e.name);
      if (e.isDirectory()) walk(p); else { n += 1; bytes += fs.statSync(p).size; }
    }
  }(OUT));
  console.log(`web-dist: ${n} files, ${(bytes / 1048576).toFixed(1)} MB`);
}

build();
